version: 2

sphinx:
    configuration: doc/conf.py

build:
    os: ubuntu-20.04
    tools:
        python: "3.12"
    jobs:
        post_install:
        # See https://github.com/pdm-project/pdm/discussions/1365
        - VIRTUAL_ENV=$(dirname $(dirname $(which python))) doc/rtd-bootstrap.sh
